

[18:34:15]
Traceback (most recent call last):
  File "C:\Users\Justin\AppData\Local\Programs\Thonny\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Justin\AppData\Local\Programs\Thonny\lib\site-packages\discord\ext\commands\core.py", line 851, in invoke
    await self.prepare(ctx)
  File "C:\Users\Justin\AppData\Local\Programs\Thonny\lib\site-packages\discord\ext\commands\core.py", line 786, in prepare
    await self._parse_arguments(ctx)
  File "C:\Users\Justin\AppData\Local\Programs\Thonny\lib\site-packages\discord\ext\commands\core.py", line 706, in _parse_arguments
    kwargs[name] = await self.transform(ctx, param)
  File "C:\Users\Justin\AppData\Local\Programs\Thonny\lib\site-packages\discord\ext\commands\core.py", line 552, in transform
    return await self.do_conversion(ctx, converter, argument, param)
  File "C:\Users\Justin\AppData\Local\Programs\Thonny\lib\site-packages\discord\ext\commands\core.py", line 505, in do_conversion
    return await self._actual_conversion(ctx, converter, argument, param)
  File "C:\Users\Justin\AppData\Local\Programs\Thonny\lib\site-packages\discord\ext\commands\core.py", line 451, in _actual_conversion
    ret = await instance.convert(ctx, argument)
  File "C:\Users\Justin\AppData\Local\Programs\Thonny\lib\site-packages\discord\ext\commands\converter.py", line 191, in convert
    raise MemberNotFound(argument)
discord.ext.commands.errors.MemberNotFound: Member "aosasodij" not found.
